const offerLink ="vnd.youtube://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbFdKWUdmTkdNMkpiWTdLSVhCc3lkMmxiUW1KUXxBQ3Jtc0ttTzRzMUozckhVUkFrZi1HZF9zOGtFaHczVnFQQ1Z3SVlKZHVQeGJDWUNtZjZxVjF2OGRrSWtncnBBZmFCSlprSG9lRThsc2IxTEQxYTQ1bkdBUEkzMnN6MmtSNlRoUWp6a2hQS25wa2l3dTNqRjNhQQ&q=securedsmcd.com%2FSiqeLBvHgS&html_redirect=1 ";

